import { Component } from '@angular/core';
import { IonApp, IonRouterOutlet } from '@ionic/angular/standalone';
import { addIcons } from 'ionicons';
import {
  add,
  aperture,
  radioButtonOn,
  radioButtonOff,
  bugOutline,
  cameraOutline,
  cameraReverse,
  cameraSharp,
  camera,
  sadOutline,
  happy,
  close,
  closeCircle,
  closeOutline,
  eye,
  eyeOffOutline,
  eyeOutline,
  flash,
  flashOff,
  flashOutline,
  image,
  imageOutline,
  imagesSharp,
  qrCodeOutline,
  refreshOutline,
  remove,
  resizeOutline,
  scanOutline,
  search,
  searchOutline,
  grid,
  gridOutline,
  star,
  starOutline,
  stop,
  sunny,
  sunnyOutline,
  videocam,
  warningOutline,
} from 'ionicons/icons';

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  imports: [IonApp, IonRouterOutlet],
})
export class AppComponent {
  constructor() {
    addIcons({
      add,
      radioButtonOn,
      radioButtonOff,
      aperture,
      bugOutline,
      sadOutline,
      happy,
      cameraOutline,
      cameraReverse,
      cameraSharp,
      camera,
      close,
      closeCircle,
      closeOutline,
      eye,
      grid,
      gridOutline,
      eyeOutline,
      eyeOffOutline,
      flash,
      flashOff,
      flashOutline,
      image,
      imageOutline,
      imagesSharp,
      qrCodeOutline,
      refreshOutline,
      remove,
      resizeOutline,
      scanOutline,
      search,
      searchOutline,
      star,
      starOutline,
      stop,
      sunny,
      sunnyOutline,
      videocam,
      warningOutline,
    });
  }
}
